purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4754600147716701
  brandStrength: 0.4480287
  lightness: 0.8115579218138009
  brandColors:
    - '#E8E7E2'
    - '#FC0376'
    - '#FCA365'
    - '#4C1E03'
    - '#BD0402'
  rhythmicContrast: 0.561683839187026
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Hilary Johnson
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8888889
layout_spectrum: 0.3996416
